import type { Declaration } from "./Declaration";

export abstract class Generator {
	protected static readonly header =
		"/* Generated by tradukisto - do not edit manually */";

	protected declarations: Record<string, Declaration> = {};

	addDeclaration(name: string, decl: Declaration) {
		if (this.declarations[name]) {
			throw new Error(`Duplicate declaration: ${name}`);
		}
		this.declarations[name] = decl;
	}

	abstract toString(repoName?: string): string;
}
