export const chunk = <T>(arr: T[], size: number) =>
	Array.from({ length: Math.ceil(arr.length / size) }, (_, i) =>
		arr.slice(i * size, i * size + size),
	);

export const operatorTypes: Record<string, string> = {
	and: "boolean",
	or: "boolean",
	not: "boolean",
	"<": "boolean",
	">": "boolean",
	"<=": "boolean",
	">=": "boolean",
	"=": "boolean",
	"!=": "boolean",
	"<>": "boolean",
	"+": "double precision",
	"-": "double precision",
	"*": "double precision",
	"/": "double precision",
	"%": "double precision",
	"^": "double precision",
	"|/": "double precision",
	"||/": "double precision",
	"!": "double precision",
	"!!": "double precision",
	"@": "integer",
	"&": "integer",
	"|": "integer",
	"#": "integer",
	"~": "integer",
	"<<": "integer",
	">>": "integer",
	"||": "text",
	like: "boolean",
	ilike: "boolean",
};
