name: continuous-integration
on:
    push:
    pull_request:
    workflow_dispatch:
jobs:
    runLint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
            - name: Install dependencies
              run: npm ci
            - name: Run linter
              run: yarn lint

    runTypecheck:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
            - name: Install dependencies
              run: npm ci
            - name: Run typechecker
              run: yarn typecheck

    runUnitTests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 24
            - name: Install dependencies
              run: npm ci
            - name: Run unit tests
              run: yarn test
